from enum import Enum


API_PREFIX = "/api/v1"
DEFAULT_DEMO_USER_ID = "user_demo_001"
PLAN_VERSION = "v0.1"


class TraceEventType(str, Enum):
    INPUT_LOG = "input_log"
    INTENT_LOG = "intent_log"
    CONSTRAINT_LOG = "constraint_log"
    MEMORY_LOG = "memory_log"
    POI_LOG = "poi_log"
    TOOL_LOG = "tool_log"
    VERIFIER_LOG = "verifier_log"
    RECOVERY_LOG = "recovery_log"
    EXECUTOR_LOG = "executor_log"
    FEEDBACK_LOG = "feedback_log"
    ERROR_LOG = "error_log"


class ErrorCode(str, Enum):
    PLAN_SCHEMA_INVALID = "PLAN_SCHEMA_INVALID"
    PLAN_TIMELINE_INVALID = "PLAN_TIMELINE_INVALID"
    PLAN_STEP_POI_NOT_FOUND = "PLAN_STEP_POI_NOT_FOUND"
    TOOL_ACTION_INVALID = "TOOL_ACTION_INVALID"
    MOCK_STATUS_MISSING = "MOCK_STATUS_MISSING"
    VERIFIER_RESULT_INVALID = "VERIFIER_RESULT_INVALID"
    RECOVERY_RESULT_INVALID = "RECOVERY_RESULT_INVALID"
    MEMORY_PRIVACY_VIOLATION = "MEMORY_PRIVACY_VIOLATION"
    CONSENSUS_VOTE_INVALID = "CONSENSUS_VOTE_INVALID"
    SOCIAL_SIGNAL_MOCK_REQUIRED = "SOCIAL_SIGNAL_MOCK_REQUIRED"
    TRACE_ID_MISSING = "TRACE_ID_MISSING"
    VERSION_NOT_SUPPORTED = "VERSION_NOT_SUPPORTED"
    PLAN_EXECUTABLE_WINDOW_EXPIRED = "PLAN_EXECUTABLE_WINDOW_EXPIRED"
    NO_TABLE_AVAILABLE = "NO_TABLE_AVAILABLE"
    ACTIVITY_FULL = "ACTIVITY_FULL"
    ROUTE_DELAY = "ROUTE_DELAY"
    WEATHER_RISK_HIGH = "WEATHER_RISK_HIGH"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    CONSENSUS_CONFLICT = "CONSENSUS_CONFLICT"
    SOCIAL_SIGNAL_MISSING = "SOCIAL_SIGNAL_MISSING"
    MEMORY_UNAVAILABLE = "MEMORY_UNAVAILABLE"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED_DEMO_USER = "UNAUTHORIZED_DEMO_USER"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


FORBIDDEN_TRACE_EVENT_TYPES = {
    "mock_call",
    "prompt_log",
    "chain_of_thought",
}

FORBIDDEN_LOG_KEYS = {
    "api_key",
    "apikey",
    "prompt",
    "prompt_log",
    "chain_of_thought",
}

USER_HIDDEN_LOG_KEYS = FORBIDDEN_LOG_KEYS | {f"failure_{'injection'}"}
